lib/mango_web/router.ex
defmodule MangoWeb.Router do
  use MangoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :frontend do
    # Add plugs related to frontend
    plug MangoWeb.Plugs.LoadCustomer
    plug MangoWeb.Plugs.FetchCart
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MangoWeb do
    pipe_through [:browser, :frontend]

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create

    get "/", PageController, :index
    get "/categories/:name", CategoryController, :show

    post "/cart", CartController, :add
    get "/cart", CartController, :show
    patch "/cart", CartController, :update
    put "/cart", CartController, :update

    get "/orders", OrderController, :index

  end

  scope "/", MangoWeb do
    pipe_through [:browser, :frontend, MangoWeb.Plugs.AuthenticateCustomer]
    # Add all routes for unauthenticated users
    get "/logout", SessionController, :delete
    get "/checkout", CheckoutController, :edit
    put "/checkout/confirm", CheckoutController, :update
  end

  # Other scopes may use custom stacks.
  # scope "/api", MangoWeb do
  #   pipe_through :api
  # end


end

lib/mango_web/views/layout_view.ex
defmodule MangoWeb.LayoutView do
  use MangoWeb, :view
  import MangoWeb.CartView, only: [cart_count: 1]

  def cart_link_text(conn) do
    raw """
    <i class="fa fa-shopping-cart"></i> <span class="cart-count">#{cart_count(conn)}</span>
    """
  end
end

lib/mango_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Mango</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  </head>
  <body>
    <%= render "app_nav.html", conn: @conn, customer: @current_customer %>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
<!-- Before that line -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/mango_web/templates/layout/app_nav.html.eex
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-
            toggle="collapse" data-target="#primary-nav">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
            <img src="/images/logo.png"/>Mango
            </a>
            </div>
            <div class="collapse navbar-collapse" id="primary-nav">
            <ul class="nav navbar-nav">
                <li><%= link "Fruits", to: Routes.category_path(@conn, :show, "fruits") %></li>
                <li><%= link "Vegetables", to: Routes.category_path(@conn, :show, "vegetables") %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link "Cart", to: Routes.cart_path(@conn, :show), class: "cart nav-link" %></li>

                <li><%= link cart_link_text(@conn), to: Routes.cart_path(@conn,:show), class: "cart nav-link" %></li>
                
                <%= if @customer do %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @customer.name %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="/orders" class="orders">My Orders</a></li>
                    <li><%= link "Log Out", to: "/logout" %></li>
                </ul>
                </li>
                <% else %>
                <li><%= link "Register", to: Routes.registration_path(@conn, :new),class: "nav-link" %></li>
                <li><%= link "Sign in", to: Routes.session_path(@conn, :new), class: "nav-link" %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>